#!/bin/sh
# Xcode Cloud post-clone script
# Generates Secrets.swift from environment variables set in App Store Connect.
# Required env vars: NOTION_TOKEN, PUSH_SECRET

set -e

SECRETS_FILE="$CI_PRIMARY_REPOSITORY_PATH/Sunzzari/Config/Secrets.swift"

if [ -z "$NOTION_TOKEN" ]; then
  echo "Error: NOTION_TOKEN environment variable is not set."
  exit 1
fi

if [ -z "$PUSH_SECRET" ]; then
  echo "Error: PUSH_SECRET environment variable is not set."
  exit 1
fi

cat > "$SECRETS_FILE" << EOF
import Foundation

/// Generated by ci_post_clone.sh — do not edit manually.
enum Secrets {
    enum Notion {
        static let token = "$NOTION_TOKEN"
    }
    enum Push {
        static let secret = "$PUSH_SECRET"
    }
}
EOF

echo "Secrets.swift generated successfully."
